# Generated by Django 3.0 on 2022-12-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("oc_lettings_site", "0002_auto_20221213_1603"),
    ]

    operations = [
        migrations.RunSQL(
            (
                """INSERT INTO profiles_profile(id, favorite_city, user_id)
               SELECT id,
                     favorite_city,
                     user_id
              FROM oc_lettings_site_profile;
           """
            )
        )
    ]
