# Generated by Django 3.0 on 2022-12-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_auto_20221213_2004'),
        ("profiles", "0002_auto_20221213_2018"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
